// Outline
export { default as ArrowDownOutline } from './arrow-down'
export { default as ArrowLeftOutline } from './arrow-left'
export { default as ArrowRightOutline } from './arrow-right'
export { default as ArrowUpOutline } from './arrow-up'
export { default as CircleOutline } from './circle'
export { default as ClickCopyOutline } from './click-copy'
export { default as CoordOutline } from './coord'
export { default as CopyOutline } from './copy'
export { default as CrossCircleOutline } from './cross-circle'
export { default as CrossOutline } from './cross'
export { default as DeleatOutline } from './deleat'
export { default as ExplainOutline } from './explain'
export { default as EyeCloseOutline } from './eye-close'
export { default as EyeOutline } from './eye'
export { default as FiltrateOutline } from './filtrate'
export { default as MobileScreenOutline } from './mobile-screen'
export { default as PlusOutline } from './plus'
// export { default as ScreenOutline } from './screen'
export { default as SearchOutline } from './search'
export { default as SOPOutline } from './sop'
export { default as SuccessCircleOutline } from './success-circle'
export { default as SuccessOutline } from './success'
export { default as TelephoneOutline } from './telephone'
export { default as VolumeOutline } from './volume'
export { default as WarningCircleOutline } from './warning-circle'
export { default as WarningOutline } from './warning'
export { default as WeChatOutline } from './we-chat'

// Fill
export { default as ArrowDownFill } from './arrow-down.fill'
export { default as ArrowLeftFill } from './arrow-left.fill'
export { default as ArrowRightFill } from './arrow-right.fill'
export { default as ArrowUpFill } from './arrow-up.fill'
export { default as CheckedFill } from './checked.fill'
export { default as DeleteFill } from './delete.fill'
export { default as NewFill } from './new.fill'
export { default as RemoveFill } from './remove.fill'
