name: Next release

on:
  push:
    tags:
      - '*'

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: build
        run: yarn && yarn build

      - name: Publish to NPM
        run: yarn run:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
